DROP INDEX IF EXISTS Anturi on Mittaukset
DROP INDEX IF EXISTS Anturi_2 on Mittaukset
# ALTER TABLE Mittaukset ADD PRIMARY KEY (Anturi, Aika);

ALTER TABLE Mittaukset ADD COLUMN id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL;
ALTER TABLE Mittaukset ADD INDEX (Aika);
ALTER TABLE Mittaukset ADD INDEX (Anturi);
ALTER TABLE Anturit ADD PRIMARY KEY (Anturi);
