#!/bin/bash
#TODO Debian says: insserv: warning: script 'homesensor' missing LSB tags and overrides
HOMESENSOR_HOME=/home/homesensor/homesensor
cd $HOMESENSOR_HOME/detector && screen -S homesensor -d -m python detector.py
